version: '3.7'
services: 
  app:
    build: .
    command: php -S 0.0.0.0:7000
    volumes:
      - .:/app
      - composer-vendor:/app/vendor
    ports: 
      - 7000:7000
  
volumes:
  composer-vendor:
